#!/bin/bash

nohup python3 app/main.py --file "dataset/transaction/jan-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jan-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/feb-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/feb-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/mar-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/mar-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/apr-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/apr-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/may-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/may-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jun-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jun-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jul-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jul-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/aug-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/aug-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/sep-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/sep-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/oct-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/oct-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/nov-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/nov-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/dec-22.csv" --use-llm --llm-model "qwen2.5:7b" > logs/dec-22.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jan-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jan-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/feb-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/feb-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/mar-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/mar-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/apr-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/apr-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/may-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/may-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jun-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jun-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jul-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jul-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/aug-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/aug-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/sep-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/sep-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/oct-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/oct-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/nov-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/nov-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/dec-23.csv" --use-llm --llm-model "qwen2.5:7b" > logs/dec-23.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jan-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jan-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/feb-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/feb-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/mar-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/mar-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/apr-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/apr-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/may-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/may-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jun-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jun-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/jul-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/jul-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/aug-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/aug-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/sep-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/sep-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/oct-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/oct-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/nov-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/nov-24.log 2>&1 &
nohup python3 app/main.py --file "dataset/transaction/dec-24.csv" --use-llm --llm-model "qwen2.5:7b" > logs/dec-24.log 2>&1 &
